context:
  version: "8.5.3"

package:
  name: capacitor-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@capacitor/cli/-/cli-${{ version }}.tgz
  sha256: d74f7e894df931541789a4bb9953d673616c21dfa891359b8aa93d24e03527ce

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - capacitor --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: |
    'Capacitor: Cross-platform apps with JavaScript and the web'
  homepage: https://capacitorjs.com/
  repository: https://github.com/ionic-team/capacitor

extra:
  recipe-maintainers:
    - danielnachun
