context:
  version: "8.5.1"

package:
  name: capacitor-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@capacitor/cli/-/cli-${{ version }}.tgz
  sha256: 551f8930a5c00ac6f78930c9c5402bdcdc6c938564c6dbd40a115ec75f719d29

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - capacitor --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: |
    'Capacitor: Cross-platform apps with JavaScript and the web'
  homepage: https://capacitorjs.com/
  repository: https://github.com/ionic-team/capacitor

extra:
  recipe-maintainers:
    - danielnachun
