context:
  version: "7.4.2"

package:
  name: capacitor-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@capacitor/cli/-/cli-${{ version }}.tgz
  sha256: 5f59c00875a5a766b6891de992aec61ac85c4e92da1750353cc0c9fb7416e68a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - capacitor --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: |
    'Capacitor: Cross-platform apps with JavaScript and the web'
  homepage: https://capacitorjs.com/
  repository: https://github.com/ionic-team/capacitor

extra:
  recipe-maintainers:
    - danielnachun
