context:
  version: "8.3.1"

package:
  name: capacitor-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@capacitor/cli/-/cli-${{ version }}.tgz
  sha256: 5f75e476af9ba0b587d597b7b9ae50089cb84a929250bfc9b8fada281a8acd84

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - capacitor --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: |
    'Capacitor: Cross-platform apps with JavaScript and the web'
  homepage: https://capacitorjs.com/
  repository: https://github.com/ionic-team/capacitor

extra:
  recipe-maintainers:
    - danielnachun
