context:
  version: "8.1.0"

package:
  name: capacitor-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@capacitor/cli/-/cli-${{ version }}.tgz
  sha256: 0faa008e76c4d92f305babe37ccbe4eebd70b326f46a59f54b18d2fe9a7bfd8a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - capacitor --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: |
    'Capacitor: Cross-platform apps with JavaScript and the web'
  homepage: https://capacitorjs.com/
  repository: https://github.com/ionic-team/capacitor

extra:
  recipe-maintainers:
    - danielnachun
